#!/bin/bash

export CUDA_VISIBLE_DEVICES=0

python src/train_fusionnet.py \
--train_images_path training/kitti/unsupervised/kitti_train_nonstatic_images.txt \
--train_sparse_depth_path training/kitti/unsupervised/kitti_train_nonstatic_sparse_depth.txt \
--train_intrinsics_path training/kitti/unsupervised/kitti_train_nonstatic_intrinsics.txt \
--val_image_path validation/kitti/kitti_val_image.txt \
--val_sparse_depth_path validation/kitti/kitti_val_sparse_depth.txt \
--val_ground_truth_path validation/kitti/kitti_val_ground_truth.txt \
--n_batch 8 \
--n_height 320 \
--n_width 768 \
--normalized_image_range 0 1 \
--outlier_removal_kernel_size 7 \
--outlier_removal_threshold 1.5 \
--max_pool_sizes_spatial_pyramid_pool 13 17 19 21 25 \
--n_convolution_spatial_pyramid_pool 3 \
--n_filter_spatial_pyramid_pool 8 \
--encoder_type_scaffnet vggnet08 spatial_pyramid_pool batch_norm \
--n_filters_encoder_scaffnet 16 32 64 128 256 \
--decoder_type_scaffnet multi-scale batch_norm \
--n_filters_decoder_scaffnet 256 128 128 64 32 \
--min_predict_depth_scaffnet 1.5 \
--max_predict_depth_scaffnet 80.0 \
--encoder_type_fusionnet vggnet08 \
--n_filters_encoder_image_fusionnet 48 96 192 384 384 \
--n_filters_encoder_depth_fusionnet 16 32 64 128 128 \
--decoder_type_fusionnet multi-scale \
--n_filters_decoder_fusionnet 256 128 128 64 32 \
--scale_match_method_fusionnet local_scale \
--scale_match_kernel_size_fusionnet 5 \
--min_predict_depth_fusionnet 1.5 \
--max_predict_depth_fusionnet 100.0 \
--min_multiplier_depth_fusionnet 0.25 \
--max_multiplier_depth_fusionnet 4.00 \
--min_residual_depth_fusionnet -1000.0 \
--max_residual_depth_fusionnet 1000.0 \
--weight_initializer xavier_normal \
--activation_func leaky_relu \
--learning_rates 2e-4 1e-4 5e-5 \
--learning_schedule 18 24 30 \
--freeze_scaffnet_modules all \
--augmentation_probabilities 1.00 \
--augmentation_schedule -1 \
--augmentation_random_crop_type horizontal bottom anchored \
--augmentation_random_flip_type horizontal \
--w_color 0.20 \
--w_structure 0.80 \
--w_sparse_depth 0.10 \
--w_smoothness 0.01 \
--w_prior_depth 0.10 \
--threshold_prior_depth 0.30 \
--w_weight_decay_depth 0.00 \
--w_weight_decay_pose 0.00 \
--min_evaluate_depth 1e-3 \
--max_evaluate_depth 100.0 \
--n_step_per_summary 5000 \
--n_image_per_summary 4 \
--n_step_per_checkpoint 5000 \
--checkpoint_path trained_fusionnet/kitti/fusionnet_vgg08 \
--start_step_validation 15000 \
--scaffnet_model_restore_path pretrained_models/scaffnet/vkitti/scaffnet-vkitti.pth \
--device cuda \
--n_thread 8
